lora_explanation:
  lora:
    alpha: 32
    dropout: 0.1
    r: 16
    target_modules:
    - q_proj
    - v_proj
  model:
    name: Salesforce/blip2-opt-2.7b
  training:
    batch_size: 1
    epochs: 8
    learning_rate: 5.0e-05
    warmup_steps: 50
    weight_decay: 0.01
minicpm_anomaly:
  model:
    anomaly_threshold: 0.1
    latent_dim: 512
    minicpm_weight: 0.3
    use_minicpm: true
  training:
    batch_size: 2
    epochs: 20
    learning_rate: 0.0001
    patience: 8
    weight_decay: 1.0e-05
session_info:
  dataset: MVTec AD Wallplugs
  description: MiniCPM異常検知 + LoRA説明生成の統合学習
  session_id: '20250928_165841'
